ifeq ($(CC_TYPE),GCC)
    CFLAGS+= -flax-vector-conversions -static -DVWIDTH=256 -DUPPERLIMIT=512
else
    ifeq ($(ENVIRONMENT),riscv64)
        CFLAGS+= -flax-vector-conversions -static -DVWIDTH=256 -DUPPERLIMIT=512 -mrvv-vector-bits=2048 -Rpass=.*
    else
        CFLAGS+= -flax-vector-conversions -static -DVWIDTH=256 -DUPPERLIMIT=512 -march=armv8.2-a+sve -msve-vector-bits=2048 -Rpass=.*
    endif
endif
