ifeq ($(CC_TYPE),GCC)
    CFLAGS+= -flax-vector-conversions -static -DVWIDTH=32 -menable-experimental-extensions -DUPPERLIMIT=512
else
    ifeq ($(ENVIRONMENT),riscv64)
        CFLAGS+= -flax-vector-conversions -static -DVWIDTH=32 -menable-experimental-extensions -DUPPERLIMIT=512 -mcpu=sifive-x280
    else
        CFLAGS+= -flax-vector-conversions -static -DVWIDTH=0 -DUPPERLIMIT=512 -march=armv8.2-a+sve
    endif
endif