
ifeq ($(CC_TYPE),GCC)
CFLAGS+= -flax-vector-conversions -static -DVWIDTH=16 -menable-experimental-extensions -DUPPERLIMIT=256
else
CFLAGS+= -flax-vector-conversions -static -DVWIDTH=16 -menable-experimental-extensions -DUPPERLIMIT=256 -mcpu=sifive-x280
endif